#!/bin/bash
cp -r [!.git]* ~

if [ ! -f ~/bin/vcprompt ]; then
	echo "installing vcprompt"
	curl -sL https://github.com/xvzf/vcprompt/raw/master/bin/vcprompt > ~/bin/vcprompt
	chmod 755 ~/bin/vcprompt
fi

