#!/bin/bash
cp -Rv ./ ~/
#find ~ -name '.git' -exec rm -rf {} \;

if [ ! -f ~/bin/vcprompt ]; then
	echo "installing vcprompt"
	curl -sL https://raw.github.com/djl/vcprompt/master/bin/vcprompt ~/bin/vcprompt
	chmod 755 ~/bin/vcprompt
fi

